import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const db = new PrismaClient({ adapter });

// 22 kode departemen diambil dari Daily_Out.xlsx (file tracking manual PT JAI).
// Nama lengkap belum tersedia di file sumber -- untuk sementara nama = kode,
// perlu dikonfirmasi & diedit lewat halaman Kelola Departemen (superadmin).
const DEPARTEMEN_KODE = [
  "COPY",
  "DE",
  "EXIM",
  "FA",
  "GAGS",
  "HR",
  "IR",
  "IT",
  "MPC",
  "MTC",
  "NYS",
  "PD",
  "PE",
  "PP",
  "PPC",
  "PROD",
  "PURCH",
  "QA",
  "QSA",
  "SC",
  "TRN",
  "WHS",
];

// STAT: departemen internal untuk akun superadmin & admin stationery
// (bukan departemen operasional perusahaan, cuma penampung akun sistem).

async function main() {
  const deptRecords: Record<string, { id: number }> = {};

  for (const kode of DEPARTEMEN_KODE) {
    deptRecords[kode] = await db.departemen.upsert({
      where: { kode },
      update: {},
      create: { nama: kode, kode },
    });
  }

  const stat = await db.departemen.upsert({
    where: { kode: "STAT" },
    update: {},
    create: { nama: "Stationery (internal)", kode: "STAT" },
  });

  const passwordHash = await bcrypt.hash("password123", 10);

  await db.user.upsert({
    where: { nik: "22071" },
    update: {},
    create: { nik: "22071", nama: "Budi Santoso", passwordHash, role: "staf", departemenId: deptRecords["QA"].id },
  });
  await db.user.upsert({
    where: { nik: "11769" },
    update: {},
    create: { nik: "11769", nama: "Lisa M.", passwordHash, role: "atasan_departemen", departemenId: deptRecords["QA"].id },
  });
  await db.user.upsert({
    where: { nik: "90001" },
    update: {},
    create: { nik: "90001", nama: "Superadmin", passwordHash, role: "superadmin", departemenId: stat.id },
  });
  await db.user.upsert({
    where: { nik: "90002" },
    update: {},
    create: { nik: "90002", nama: "Admin Stationery", passwordHash, role: "admin_stationery", departemenId: stat.id },
  });

  // 240 item diimpor dari Daily_Out.xlsx, kategori mengikuti 4 sheet aslinya:
  // ATK -> barang_umum, catridge#toner#tinta -> catridge_toner_tinta,
  // Paper & other -> kertas, checksheet -> checksheet.
  // Stok awal semua di-set 0 karena file sumber tidak mengisi kolom STOCK
  // AWAL -- perlu direstock manual lewat halaman Restock.
  const items = [
    { nama: "C/S DEFFECT", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "C/S HOUSING A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "C/S PREFENTIVE APLIKATOR", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "C/S SIMPLE CROSS SECTION", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "VOLTAGE TEST", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DAILY REPORT CUTTING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DEF TAG F/A", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DEF TAG P/A", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DEF TAG PINK", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DELIVARY PACKING RANGKAP 1", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "DELIVARY PACKING RANGKAP 2", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM BERITA ACARA LAP. KEJADIAN", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM BUKTI PENERIMAAN BARANG", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN BEROBAT", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN KELUAR LOKASI", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN KERJA", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN KERJA KETINGGIAN", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN KERJA PANAS", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM IJIN KERJA WORKSHOP", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM KEHADIRAN TRAINING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM OT", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM PENGAMBILAN CF/AF", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM PERINCIAN BEA KNDRN OPR", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM RECEIPT", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM REPRESENTATION DECLARATION", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM SPKL", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "FORM TAMU", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "GEL SHEET", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LIST CARTON CODE", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKI A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKI CUTTING (NEW)", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKI F/A", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO & LKI  MANUAL CRIMPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO & LKI  MANUAL CRIMPING BIG SIZE", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO & LKI HEAT SHRINK (RAYCHEM)", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO & LKI JOINT CRIMPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO CHECK TPO", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO CUTTING A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO END STRIPPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO END STRIPPING A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO F/A", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO GUN SOLDER", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO JOINT TAPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO MACHINE DOWN TIME", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO MANUAL CRIMPING A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO MANUAL TAPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO MIDDLE STRIPPING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO QUALITY TUBE", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO ROLLING MACHINE TUBE", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO TORQUE", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO TUBE ACC A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO TUBE ACCESSORIES", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO WELDING BONDER", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO WIRE TWISTING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LKO WIRE TWISTING A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LOT ID A/B", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "LOT MANAGEMENT BONDING", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "PART REQUISITION N/P", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "PART REQUISTITION", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "PERGANTIAN PART HJ MTC", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SET UP CARD", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SET UP CARD EJ (NEW)", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SET UP VERIFICATION", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SET UP VERIFICATION ALVUS (NEW/SPC)", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SURAT JALAN EXIM", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "SURAT KELUAR BARANG", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "TANDA TERIMA DOCUMENT", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "BUKU SUB ASSY&LAY OUT DEFFECT TRACKING REMOVAL TOOL", kategori: "checksheet", satuan: "lembar", stok: 0, stokMinimum: 10 },
    { nama: "CATRIDGE CANON 750 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 751 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 751 CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 751 MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 751 YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TONER COMPATIBLE 16X", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TONER COMPATIBLE 80A/05A", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TONER COMPATIBLE HP 93A", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T6641 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T6642 CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T7663 MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T7664 YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "RIBBON PRINTONIX P300 P600", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "PITA PRINTRONIX PN 255049-103/P8000-P7000", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 725 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 726 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 726 CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 726 MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE CANON 726 YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE HP 950XL BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE HP 951XL CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE HP 951XL MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE HP 951XL YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T003 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T003 CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T003 MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "CATRIDGE EPSON T003 YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TONER COMPATIBLE HP 30A", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "DRUM UNIT 32A", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA EPSON Y001 BLACK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA EPSON Y001 CYAN", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA EPSON Y001 MAGENTA", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA EPSON Y001 YELLOW", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA BROTHER DCP 5000 C", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA BROTHER DCP 5000 M", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA BROTHER DCP 5000 Y", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "TINTA BROTHER DCP 6000 BK", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "BROTHER INK CATRIDGE D-60 BLACK 108ml", kategori: "catridge_toner_tinta", satuan: "pcs", stok: 0, stokMinimum: 5 },
    { nama: "KERTAS A4 70 GR SIDU", kategori: "kertas", satuan: "rim", stok: 0, stokMinimum: 5, jenisKertas: "A4" },
    { nama: "KERTAS A3 70 GR SIDU", kategori: "kertas", satuan: "rim", stok: 0, stokMinimum: 5, jenisKertas: "A3" },
    { nama: "KERTAS F4 70 GR SIDU", kategori: "kertas", satuan: "rim", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS A5 80 GR SIDU", kategori: "kertas", satuan: "rim", stok: 0, stokMinimum: 5, jenisKertas: "A5" },
    { nama: "CF 14 7/8 X 11 1 PLY SIDU (AS 400)", kategori: "kertas", satuan: "box", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS PLOTTER A0", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS PLOTTER A0 (lebih 1 M)", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS PLOTTER A0 ART PAPER", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS HVS 80 GR AO 36\"", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "KERTAS HVS 80 GR A1 50 M", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "ART PAPER", kategori: "kertas", satuan: "pack", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "OTHER", kategori: "kertas", satuan: "rim", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "TISSU SISUI", kategori: "kertas", satuan: "pack", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "LAKBAN COKLAT NACHI", kategori: "kertas", satuan: "roll", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "CLEANER BOTOL", kategori: "kertas", satuan: "botol", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "REFIL CLEAR", kategori: "kertas", satuan: "botol", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "REFIL STELLA MATIC", kategori: "kertas", satuan: "botol", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "STELLA MATIC MESIN", kategori: "kertas", satuan: "unit", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "TISSU", kategori: "kertas", satuan: "pack", stok: 0, stokMinimum: 5, jenisKertas: "Others" },
    { nama: "AMPLOP AIRMAIL A3 TALI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "AMPLOP COKLAT FOLIO KOP", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "AMPLOP GAJI COKLAT", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "AMPLOP PUTIH", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "AMPLOP COKLAT FOLIO POLOS", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI A2 ALKALINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI A3 ALKALINE", kategori: "barang_umum", satuan: "psg", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI ABC TYPE C", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI ABC TYPE D", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BOARDMARKER SNOWMAN", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BODY CLIPS", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BOLLPOINT SNOWMAN V2", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BOX FILE JUMBO BLUE BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BUKU HARDCOVER 100 HAL KIKY", kategori: "barang_umum", satuan: "bk", stok: 0, stokMinimum: 10 },
    { nama: "BUKU HARDCOVER 200 HAL KIKY", kategori: "barang_umum", satuan: "bk", stok: 0, stokMinimum: 10 },
    { nama: "BUKU TULIS BOSS", kategori: "barang_umum", satuan: "bk", stok: 0, stokMinimum: 10 },
    { nama: "BUSSINES FILE A4", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CALCULATOR CITIZEN 12 DGT  SDC 868 L", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CALCULATOR CT 12 DIGIT 555", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CLIPBOARD KAYU", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CORRECTION TAPE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CUTTER JOYCO L-500SG", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CUTTER JOYCO L-500", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "CUTTER KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "DISPENSER TAPE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "DOUBLE TAPE 1\" NACHI", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "DOUBLE TAPE 2\" NACHI", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "GANTUNGAN KUNCI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "GUNTING BESAR", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "GUNTING KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "HANG MAP", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISI BOLLPOINT SNOWMAN V2 (UJ LANCIP)", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISI CUTTER BESAR KENKO", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISI CUTTER KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISI PENSIL MEKANIK PPL 0,5 2B PILOT", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISI STAPLER BESAR", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "ISI STAPLER KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ISOLASI BENING 1\" NACHI (KUNING)", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "ISOLASI BENING 1/2\" NACHI (KUNING)", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS A4 80GR WARNA SIDU", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS WARNA LIME /CYBER HP GREEN", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS WARNA ORANGE/GOLD", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS WARNA GREY(concord)", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS WARNA KREM(concord)", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS TAN (coklat)", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KERTAS BUFFALO", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "KWITANSI MINI", kategori: "barang_umum", satuan: "bk", stok: 0, stokMinimum: 10 },
    { nama: "LAKBAN BENING 2\" NACHI", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "LAKBAN HITAM 2\" NACHI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "LAKBAN KUNING 2\" NACHI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "LAKBAN BIRU 2\" NACHI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "LAKBAN MERAH 2\" NACHI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "LEM UHU BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "MAGIC TAPE 3/4", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "MAP KERTAS BIASA DJAGO MERAH", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "MAP L CLEAR HOLDER FOLIO", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "MARKER OHP 853 F BLACK", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "Marker OHP 853 F  COLOUR", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "Marker OHP 854 M BLACK", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "Marker OHP 854 M COLOUR", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "MARKER SNOWMAN / ARTLINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "NAME TAG", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PLASTIC ID PUNGGUNG", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "NOTES", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ODNER A4 BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ODNER FOLIO BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ORDNER A4 TIPIS", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ORDNER 1/2-FOLIO", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PLASTIK TRANSPARANT YASHICA", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PLASTIK LAMINATING FOLIO", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "PLASTIK LAMINATING A3 SAKURAI", kategori: "barang_umum", satuan: "lbr", stok: 0, stokMinimum: 10 },
    { nama: "PAINTMARKER SILVER ARTLINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAINTMARKER WHITE ARTLINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAINTMARKER GOLD ARTLINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAINTMARKER PURPLE ARTLINE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAPER CLIPS PLASTIK BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAPER FASTENER", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAPER NEW FAX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PEMOTONG LAKBAN BESI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENGGARIS MIKA 30 CM", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENGGARIS BAJA", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENGHAPUS JOYCO PUTIH", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENGHAPUS WHITE BOARD", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENSIL MEKANIK PILOT", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PENSIL STEADLER 2B", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PERFORATOR BESAR", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PERFORATOR KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "POST IT 653 (KECIL)", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "POST IT 654 (BESAR)", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "POST IT SIGN HERE", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PUSH PIN KENKO", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "RAUTAN PENSIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "RIBBON CATRIDGE #8853", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "RIBBON CATRIEDGE LQ 2180", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "SHEET PROTECTOR A3 BANTEX", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "SHEET PROTECTOR A4 DAICHI", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "SPIDOL SNOWMAN 12WARNA", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "SPIDOL SNOWMAN KECIL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "STABILLO BOSS", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "STAPLER BESAR", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "STAPLER KECIL MAX", kategori: "barang_umum", satuan: "roll", stok: 0, stokMinimum: 10 },
    { nama: "STIKER LABEL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "TALI ID CARD", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "TALI RAFIA", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "TINTA TRODAT", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "TINTA YAMURA", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "TIPE-X BOTOL (UJUNG BESI) KENKO", kategori: "barang_umum", satuan: "pack", stok: 0, stokMinimum: 10 },
    { nama: "BALLPOINT HI TECH", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "ARTLINE EK 100", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "DIAMOND STOPMAP 2002", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "PAINT MARKER PX-20", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI KOTAK 9 VOLT", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI KANCING MAXELL CR 2032", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
    { nama: "BATERAI KANCING LR1130 MAXELL", kategori: "barang_umum", satuan: "pcs", stok: 0, stokMinimum: 10 },
  ] as const;

  await db.item.createMany({ data: items as any, skipDuplicates: true });

  console.log(`Seed selesai: ${DEPARTEMEN_KODE.length + 1} departemen, 4 user, ${items.length} item.`);
  console.log("Password default semua akun contoh: password123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
